### ISSUE TITLE
mztab file exported from PD2.2 meet error in raw_filenames

### ISSUE THREAD

**Issue by iszhi** [cbielow/PTXQC#77] opened 2020-03-02 14:09 UTC
Recently, I need to do the quality control for my result exported from PD2.2. Unfortunately, I can't do it normally. I meet this error. Could you check it?

![PTXQCerror](https://user-images.githubusercontent.com/33443222/75683673-e29d5400-5c97-11ea-9ba7-64f2a2a915e7.jpg)

**Comment by cbielow** [comment] 2020-03-02 15:15
Sure.  Thanks for reporting!
Could you upload the the mzTab file somewhere and send me the link?
Thanks!

**Comment by iszhi** [comment] 2020-03-03 10:02
@cbielow Thanks. But sorry at the moment, I'm not allowed to send the mzTab file. I'll try to find a way to resolve this.

**Comment by cbielow** [comment] 2020-03-03 12:17
ok, I see.

Two options: just send the first lines of the MzTab file (all that start with `MTD`) -- that is sufficient to debug the problem. I can almost guess what it is, but just to make sure.
Alternatively, just look at the lines
`MTD	ms_run[1]-location	...`
and
`MTD	ms_run[2]-location ...` etc in your mzTab file.
The third item (here marked as `...`) should say something meaningful for all Raw files that were combined into the mzTab.
Is that the case here?

**Comment by cbielow** [comment] 2020-03-04 13:13
Ok, thanks for the file.
The problem is a single (invalid) character in the `MTD	ms_run[1]_location...` lines, which is not according to mzTab specs. It should be `MTD	ms_run[1]-location...`. Thus, our parser does not recognize the lines and fails.

I will relax the rules a bit, so output from PD2.2 will be accepted in future releases of PTXQC (1.0.3 and above).
For the time being, manually change these lines and replace `_location` by `-location`. This should allow you to process the file with PTXQC 1.0.0 and above.
Please note that I do not have access to the mzTab files PD2.2 writes. The information in there is probably only enough for a few metrics. To get the most out of mzTab, you have to use the [OpenMS QualityControl](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html) (--> TOPP tools --> QualityControl) tool.

Hope this helps.

**Closed** 2020-03-04 13:20 UTC
