### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, page, value = 1) :    replacement has 1 row, data has 0 [UTF-8 BOM issue]

### ISSUE THREAD

**Issue by GeorgTascher** [cbielow/PTXQC#130] opened 2023-05-15 15:54 UTC
Dear Chris,

I recently started to use a newer version of MaxQuant (2.4.0.0) and PTXQC crashes directly:

Starting to work on PAR: MQ Parameters ...
Error in `$<-.data.frame`(`*tmp*`, page, value = 1) : 
  replacement has 1 row, data has 0

I use PTXQC v1.0.14 on a Win 2012 server using R Studio 2022.02.2 with running R 3.6.3 (a bit old, I know....)
I didn`t try other versions than my "stable" MaxQuant release (1.6.17.0), so I don`t know if this problem was introduced already some MQ-versions before or only in this version. What I can say is that the "parameters.txt" is different between the two versions....

Is this problem known?

Cheers and thanks for this REALLY useful tool!
Georg

**Comment by cbielow** [comment] 2023-05-15 20:55
Hi Georg,

can you provide the full txt folder?! This would make it much easier to identify the problem.

**Comment by GeorgTascher** [comment] 2023-05-15 22:58
Hi Chris,
Thank you for your prompt reply!
Sure, sorry, here is the link to WeTransfer, folder was to big to upload it here:
[https://we.tl/t-d9KDmKO9Wz](url)

**Comment by cbielow** [comment] 2023-05-17 14:18
Hi Georg,

the `problem` here originates from a new encoding which MaxQuant uses for its txt files.
They now start each file with a [byte-order mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark), which trips up the R function for reading text files.
This is especially weird, since the encoding is UTF-8, and using a BOM for UTF-8 is not recommended.

Well, the problem is fixed in the latest PTX-QC release (1.0.16), which you can get from Github (see installation instructions on main page) or wait a few days until the CRAN release has trickled through.

Thanks for reporting the problem!

**Closed as completed** 2023-05-17 14:23 UTC

**Comment by cbielow** [comment] 2023-05-24 04:51
Glad to hear it works!
Thanks again for reporting!
